project:
  type: website
  output-dir: docs

website:
  comments: 
    utterances:
      repo: quarto-dev/quarto-web
      theme: github-light
  title: "Add name here"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - projects.qmd
      - posts.qmd
      - resources.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



